<div class="card border-0 shadow-sm rounded-4 h-100">

    <div class="card-header bg-white border-0">

        <div class="d-flex justify-content-between align-items-center">

            <div>

                <h5 class="fw-bold text-orange mb-1">

                    💡 Trade Recommendations

                </h5>

                <small class="text-muted">

                    Latest recommendations generated by the Trade Recommendation Engine

                </small>

            </div>

            <span class="badge bg-primary">

                {{ count($recommendations) }} Items

            </span>

        </div>

    </div>

    <div class="card-body p-0">

        <div class="table-responsive">

            <table class="table table-hover align-middle mb-0">

                <thead class="table-light">

                <tr>

                    <th>Country</th>
                    <th>Action</th>
                    <th>Priority</th>
                    <th>Recommendation</th>
                    <th>Generated</th>

                </tr>

                </thead>

                <tbody>

                @forelse($recommendations as $item)

                    <tr>

                        <td>

                            <div class="d-flex align-items-center">

                                <img src="{{ $item->country->flag }}"
                                     width="34"
                                     class="rounded shadow-sm me-2">

                                <div>

                                    <strong>

                                        {{ $item->country->country_name }}

                                    </strong>

                                    <br>

                                    <small class="text-muted">

                                        {{ $item->country->country_code }}

                                    </small>

                                </div>

                            </div>

                        </td>

                        <td>

                            <span class="fw-semibold text-dark">

                                {{ $item->trade_action }}

                            </span>

                        </td>

                        <td>

                            @php

                                $priorityColor = match(strtolower($item->priority)) {

                                    'critical' => 'danger',

                                    'very high' => 'warning',

                                    'high' => 'warning',

                                    'medium' => 'primary',

                                    'low' => 'success',

                                    default => 'secondary'

                                };

                            @endphp

                            <span class="badge bg-{{ $priorityColor }}">

                                {{ $item->priority }}

                            </span>

                        </td>

                        <td style="min-width:250px">

                            {{ $item->recommendation }}

                            <br>

                            <small class="text-muted">

                                {{ $item->business_reason }}

                            </small>

                        </td>

                        <td>

                            {{ optional($item->generated_at)->format('d M Y H:i') }}

                        </td>

                    </tr>

                @empty

                    <tr>

                        <td colspan="5" class="text-center py-5">

                            No recommendation available.

                        </td>

                    </tr>

                @endforelse

                </tbody>

            </table>

        </div>

    </div>

</div>